export const CITY_LOCAL_CONTENT: Record<string, {
  localSpecifics: string;
  nearbyAreas: string[];
  projectSnippet: string;
}> = {
  "midlothian-tx": {
    localSpecifics: "Midlothian homeowners know that red clay dust, Ellis County pollen, and summer humidity create the perfect conditions for algae and mold growth on siding. The city's mix of brick, vinyl, and stucco homes requires specialized soft-wash techniques to clean safely without damaging exterior finishes. Older neighborhoods near downtown often feature historic properties where pressure must be carefully controlled. Recent developments in areas like Midlothian Meadows and Walnut Grove have modern siding that benefits from regular maintenance to prevent long-term staining. Local HOAs increasingly require clean exteriors, making professional pressure washing an essential service for maintaining property values in this growing Ellis County community.",
    nearbyAreas: ["waxahachie-tx", "red-oak-tx"],
    projectSnippet: "Recent soft-wash project on Walnut Ridge Drive removed five years of algae buildup from vinyl siding without damaging the paint or trim."
  },
  "waxahachie-tx": {
    localSpecifics: "Waxahachie's historic downtown district features Victorian-era homes and commercial buildings with delicate painted surfaces, ornate trim, and aging masonry that demand low-pressure cleaning methods. The city's position in Ellis County means properties face persistent red dust from surrounding farmland combined with oak and pecan tree droppings that stain roofs and driveways. Newer subdivisions around FM 66 and Highway 287 feature modern composite siding prone to algae streaking in the humid Texas climate. Irrigation runoff from St. Louis limestone-heavy soil creates distinctive rust staining on concrete surfaces. Local building codes and historical preservation guidelines often require pre-approval for exterior cleaning on properties in designated historic zones.",
    nearbyAreas: ["midlothian-tx", "ennis-tx"],
    projectSnippet: "Restored a 1920s Queen Anne Victorian on College Street using ultra-gentle soft wash to preserve original paint while removing decades of organic growth."
  },
  "cedar-hill-tx": {
    localSpecifics: "Cedar Hill properties situated on sloped terrain near Joe Pool Lake and Cedar Hill State Park experience unique drainage patterns that cause concentrated algae growth on north-facing walls and foundation areas. The city's strict HOA communities in developments like The Peninsula and High Pointe require regular exterior maintenance with specific standards for approved cleaning methods. Local limestone-based soil creates persistent white mineral deposits on driveways and retaining walls that require specialized treatment beyond standard pressure washing. Homes in wooded areas near the greenbelt face accelerated organic growth from tree canopy shade and increased humidity, necessitating annual soft-wash treatments to prevent permanent staining of siding materials.",
    nearbyAreas: ["desoto-tx", "grand-prairie-tx"],
    projectSnippet: "Eliminated severe black algae streaks from a lakeside property's brick and stone exterior using targeted soft-wash chemistry that protected nearby landscaping."
  },
  "mansfield-tx": {
    localSpecifics: "Mansfield's rapid residential growth has created numerous master-planned communities with strict architectural standards requiring pristine exterior appearance. The area's clay-heavy soil kicked up by construction and wind creates persistent red-brown staining on white and light-colored siding that standard rain cannot remove. Commercial properties along Highway 287 and FM 917 face heavy traffic pollution requiring quarterly pressure washing to maintain professional curb appeal. Local brick homes common in neighborhoods like Walnut Creek and Lakes of Mansfield develop efflorescence (white mineral deposits) requiring proper cleaning techniques to avoid damage. The city's mix of mature trees and new construction means properties face both established organic growth and fresh construction dust accumulation.",
    nearbyAreas: ["arlington-tx", "midlothian-tx"],
    projectSnippet: "Commercial storefront restoration on Matlock Road removed eight months of traffic film and restored the building's appearance ahead of new tenant move-in."
  },
  "red-oak-tx": {
    localSpecifics: "Red Oak's semi-rural character means properties often sit on larger lots with extensive concrete areas including long driveways, RV pads, and outbuilding foundations that accumulate oil stains from vehicles and equipment. The community's agricultural heritage results in seasonal pollen blasts from surrounding farmland that coat roofs and siding with yellow-green buildup requiring soft-wash removal. Many homes feature metal roofs popular in the area that need gentle cleaning to avoid damaging protective coatings. Well water common in the area creates distinctive iron staining on concrete surfaces when irrigation systems spray onto driveways and sidewalks. Local soil conditions promote rapid moss growth in shaded areas, particularly on north-facing surfaces and areas with poor drainage.",
    nearbyAreas: ["midlothian-tx", "ovilla-tx"],
    projectSnippet: "Tackled a 200-foot driveway with deep-set oil stains from farm equipment, restoring the concrete to near-original condition in a single afternoon."
  },
  "ovilla-tx": {
    localSpecifics: "Ovilla's small-town atmosphere features a mix of older ranch-style homes and new construction, each presenting unique cleaning challenges from age-related staining to construction dust accumulation. Properties near Ovilla Road and Red Oak Creek experience elevated humidity levels that accelerate mold and mildew growth on siding, particularly during spring and fall. The area's predominant brick construction develops green and black biofilm in mortar joints requiring specialized low-pressure techniques to clean without eroding grout. Rural properties often have extensive shop buildings, barns, and covered areas where birds and wildlife create persistent staining that needs professional treatment. Local well water with high mineral content creates rust staining on any surface contacted by irrigation spray.",
    nearbyAreas: ["red-oak-tx", "midlothian-tx"],
    projectSnippet: "Cleaned a decades-old brick ranch home, removing biofilm from mortar lines and restoring the original red brick color without damage."
  },
  "venus-tx": {
    localSpecifics: "Venus properties in this quiet Johnson County community face unique challenges from surrounding agricultural operations including wind-blown fertilizer dust and seasonal harvest debris that coat exterior surfaces. The area's country living atmosphere means many homes have detached workshops, barns, and storage buildings with metal siding requiring specialized cleaning to prevent oxidation damage. Properties along FM 157 deal with road dust and rural traffic grime necessitating regular pressure washing of foundations and lower siding sections. Local soil creates distinctive red-clay staining on concrete that becomes more pronounced during rainy seasons when runoff carries clay particles onto driveways. Homes with well water often have sprinkler systems that leave hard water deposits on siding and windows requiring chemical treatment in addition to pressure washing.",
    nearbyAreas: ["midlothian-tx", "burleson-tx"],
    projectSnippet: "Restored a metal workshop building's siding and roof, removing years of oxidation and agricultural dust while protecting the galvanized coating."
  },
  "arlington-tx": {
    localSpecifics: "Arlington's urban density and position between Dallas and Fort Worth create elevated pollution levels that coat building exteriors with traffic film and industrial particulates requiring professional removal. Properties near entertainment districts around AT&T Stadium and Globe Life Field face accelerated soiling from heavy pedestrian and vehicle traffic. The city's mature neighborhoods feature established trees that deposit organic material year-round, while newer developments deal with construction dust from ongoing commercial growth along I-20 and Highway 360 corridors. Local limestone soils common in commercial landscaping create hard water staining on storefront glass and foundations. High-rise residential properties require specialized equipment and expertise for safe, effective pressure washing of upper-floor balconies and walkways.",
    nearbyAreas: ["grand-prairie-tx", "mansfield-tx"],
    projectSnippet: "Cleaned a 12-unit townhome development near the entertainment district, removing traffic pollution and restoring curb appeal across all units in one day."
  },
  "grand-prairie-tx": {
    localSpecifics: "Grand Prairie's location along Mountain Creek Lake creates elevated humidity zones where lakefront properties experience accelerated algae and mold growth on all exterior surfaces. The city's extensive retail and commercial corridors along Belt Line Road and State Highway 360 require regular pressure washing to combat traffic pollution and maintain professional appearances in competitive markets. Industrial areas near the former Naval Air Station feature warehouses and distribution facilities with large concrete aprons that accumulate oil, grease, and tire marks from heavy truck traffic. Local clay soils combined with intense summer heat create dried mud splatter patterns on foundation walls and lower siding that standard rain cannot remove. Properties in flood-prone areas near Joe Pool Lake or Mountain Creek require post-storm cleanup including sediment removal from driveways and foundations.",
    nearbyAreas: ["arlington-tx", "irving-tx"],
    projectSnippet: "Pressure-washed a 50,000 sq ft warehouse loading dock, removing months of industrial grime and tire marks to meet OSHA safety inspection standards."
  },
  "irving-tx": {
    localSpecifics: "Irving's position near DFW Airport subjects properties to elevated jet fuel particulate fallout that creates black soiling on roofs and siding requiring specialized cleaning chemicals. The city's dense commercial development along Las Colinas Boulevard and Highway 114 generates heavy traffic pollution affecting building exteriors and requiring quarterly maintenance contracts. Older neighborhoods near MacArthur Boulevard feature original 1970s-era brick homes where mortar joints have deteriorated and require gentle pressure techniques to avoid further damage. Properties in the Las Colinas master-planned community face strict architectural review board standards for exterior appearance, often requiring professional documentation of cleaning processes. The urban heat island effect in commercial districts accelerates breakdown of exterior finishes, making regular preventive cleaning essential for longevity.",
    nearbyAreas: ["dallas-tx", "grand-prairie-tx"],
    projectSnippet: "Cleaned a Las Colinas office building's glass and granite facade, removing airport pollution and restoring the structure's professional appearance before a major tenant showing."
  },
  "dallas-tx": {
    localSpecifics: "Dallas properties in established neighborhoods like Lakewood and M Streets feature historic homes with delicate stucco, original wood siding, and vintage brick requiring expert low-pressure cleaning to preserve architectural integrity. The city's urban core generates exceptional pollution levels from vehicle traffic, HVAC condensate, and industrial operations that create black streaking on all building types. High-rise residential and commercial properties in Uptown and Downtown demand specialized high-altitude cleaning expertise with proper safety equipment and insurance coverage. Properties near major thoroughfares like Central Expressway and LBJ Freeway experience accelerated soiling from traffic emissions requiring more frequent cleaning than suburban locations. Dallas's building codes and historical preservation ordinances often mandate specific cleaning methods and prior approval for properties in designated conservation districts.",
    nearbyAreas: ["irving-tx", "fort-worth-tx"],
    projectSnippet: "Soft-washed a 1920s Tudor Revival in Lakewood, carefully cleaning decorative half-timbering and stucco without damaging the historic architectural details."
  },
  "fort-worth-tx": {
    localSpecifics: "Fort Worth's limestone-rich soil creates persistent white mineral deposits on driveways, sidewalks, and foundations that require acidic cleaning solutions for effective removal. Properties in historic districts like Fairmount and Ryan Place feature original brick and stone construction demanding gentle pressure techniques to protect century-old mortar joints. The city's established tree canopy in neighborhoods like Rivercrest and Westover Hills provides beauty but accelerates organic growth on roofs and siding through increased shade and moisture retention. Commercial properties in the Stockyards and Near Southside districts face unique challenges from tourist traffic, restaurant grease emissions, and entertainment district activities requiring specialized cleaning approaches. Properties near I-30 and I-35W corridors experience heavy traffic pollution requiring quarterly pressure washing to maintain curb appeal.",
    nearbyAreas: ["arlington-tx", "burleson-tx"],
    projectSnippet: "Restored a Stockyards-area restaurant's brick facade, removing years of grease vapor buildup while preserving the building's historic character."
  },
  "burleson-tx": {
    localSpecifics: "Burleson's position at the southern edge of the Metroplex means properties face a unique combination of urban pollution from nearby Fort Worth and rural dust from surrounding Johnson County farmland. The city's rapid residential growth has created numerous new subdivisions with modern composite siding materials that show algae streaks more prominently than traditional materials and require annual soft-wash treatment. Older homes in established areas near Old Town Burleson feature original brick and wood siding that have accumulated decades of organic growth requiring professional removal. Local water sourced from Trinity Aquifer contains minerals that create hard water staining on any surface contacted by irrigation systems. Properties along Alsbury Boulevard and Wilshire Boulevard experience heavy traffic pollution requiring regular cleaning to maintain property values.",
    nearbyAreas: ["fort-worth-tx", "venus-tx"],
    projectSnippet: "Treated a new-construction home in Hidden Creek, removing algae streaks from modern board-and-batten siding that appeared just 18 months after installation."
  },
  "desoto-tx": {
    localSpecifics: "DeSoto properties benefit from the city's tree preservation ordinances but face increased maintenance from mature oak and pecan trees that drop organic material year-round, accelerating roof staining and siding discoloration. The area's clay soil combined with sloped terrain creates erosion patterns that splash red mud onto foundations and lower siding sections during rainstorms. Properties near Interstate 35E experience accelerated soiling from traffic pollution while homes in quiet neighborhoods like Brookside and Thorntree face different challenges from organic growth in shaded areas. Local HOAs in planned communities maintain strict exterior appearance standards requiring professional cleaning to meet covenant requirements. The city's mix of brick, stone, and modern siding materials means each property requires customized cleaning approaches based on construction type and age.",
    nearbyAreas: ["cedar-hill-tx", "dallas-tx"],
    projectSnippet: "Cleaned a Thorntree community home's stamped concrete driveway and walkways, removing years of organic staining while protecting the decorative finish."
  },
  "ennis-tx": {
    localSpecifics: "Ennis properties in this historic Ellis County community face unique challenges from agricultural operations including cotton gin dust, feed mill particulates, and seasonal grain harvest debris that coat exterior surfaces during farming season. The city's position in the Blackland Prairie means heavy clay soil that creates distinctive dark brown staining on concrete surfaces when wet. Historic downtown buildings feature original brick and stone construction requiring expert restoration cleaning to remove decades of pollution without damaging aged mortar or decorative elements. Homes in newer developments along Highway 287 and FM 85 deal with construction dust from ongoing growth while older neighborhoods near downtown face accumulated pollution from railroad operations and industrial activities. Properties with metal roofs, popular in rural areas, need gentle cleaning to maintain protective coatings and prevent premature oxidation.",
    nearbyAreas: ["waxahachie-tx", "midlothian-tx"],
    projectSnippet: "Restored a downtown commercial building's original brick facade, removing 50 years of pollution and organic growth to reveal the structure's historic beauty."
  }
};
