export const SEO_CONSTANTS = {
  BUSINESS_NAME: "DFW Pristine Power Washing",
  PRIMARY_CITY: "Arlington, TX",
  SERVICE_AREA_CITIES: [
    { name: "Arlington", state: "TX", slug: "arlington-tx" },
    { name: "Mansfield", state: "TX", slug: "mansfield-tx" },
    { name: "Dallas", state: "TX", slug: "dallas-tx" },
    { name: "Fort Worth", state: "TX", slug: "fort-worth-tx" },
    { name: "Plano", state: "TX", slug: "plano-tx" },
    { name: "Southlake", state: "TX", slug: "southlake-tx" },
    { name: "Grapevine", state: "TX", slug: "grapevine-tx" },
    { name: "Colleyville", state: "TX", slug: "colleyville-tx" },
    { name: "Coppell", state: "TX", slug: "coppell-tx" },
    { name: "Carrollton", state: "TX", slug: "carrollton-tx" },
    { name: "Midlothian", state: "TX", slug: "midlothian-tx" },
    { name: "Waxahachie", state: "TX", slug: "waxahachie-tx" },
    { name: "Burleson", state: "TX", slug: "burleson-tx" },
    { name: "Hurst", state: "TX", slug: "hurst-tx" },
    { name: "Euless", state: "TX", slug: "euless-tx" },
    { name: "Frisco", state: "TX", slug: "frisco-tx" },
    { name: "Irving", state: "TX", slug: "irving-tx" },
    { name: "Keller", state: "TX", slug: "keller-tx" },
    { name: "Addison", state: "TX", slug: "addison-tx" },
    { name: "Bedford", state: "TX", slug: "bedford-tx" },
    { name: "Grand Prairie", state: "TX", slug: "grand-prairie-tx" },
    { name: "Farmers Branch", state: "TX", slug: "farmers-branch-tx" },
    { name: "Richland Hills", state: "TX", slug: "richland-hills-tx" },
    { name: "Las Colinas", state: "TX", slug: "las-colinas-tx" },
    { name: "North Richland Hills", state: "TX", slug: "north-richland-hills-tx" },
    { name: "Cedar Hill", state: "TX", slug: "cedar-hill-tx" },
    { name: "DeSoto", state: "TX", slug: "desoto-tx" },
    { name: "Ennis", state: "TX", slug: "ennis-tx" },
    { name: "Ovilla", state: "TX", slug: "ovilla-tx" },
    { name: "Red Oak", state: "TX", slug: "red-oak-tx" },
    { name: "Venus", state: "TX", slug: "venus-tx" },
  ],
  PRIMARY_SERVICES: [
    {
      name: "Pressure Washing",
      slug: "pressure-washing",
      description: "Professional high-pressure cleaning for all exterior surfaces",
    },
    {
      name: "House Washing (Soft Wash)",
      slug: "house-washing",
      description: "Gentle soft wash cleaning for siding, stucco, and painted surfaces",
    },
    {
      name: "Roof Cleaning",
      slug: "roof-cleaning",
      description: "Safe, effective roof cleaning that protects your shingles",
    },
    {
      name: "Driveway / Concrete Cleaning",
      slug: "driveway-concrete-cleaning",
      description: "Deep cleaning for driveways, sidewalks, and concrete surfaces",
    },
    {
      name: "Commercial Pressure Washing",
      slug: "commercial-pressure-washing",
      description: "Professional commercial cleaning for businesses and properties",
    },
    {
      name: "Window Cleaning",
      slug: "window-cleaning",
      description: "Streak-free window cleaning for homes and businesses",
    },
  ],
  CONTACT: {
    PHONE: "(817) 585-6388",
    PHONE_RAW: "8175856388",
    EMAIL: "joshua.dfwpristine@gmail.com",
    ACTUAL_EMAIL: "joshua.dfwpristine@gmail.com",
  },
  SITE_URL: "https://dfwpristinepowerwashing.com",
  NAP: {
    STREET: "",
    CITY: "Arlington",
    STATE: "TX",
    ZIP: "",
  },
  HOURS: "Open 24 hours",
  SOCIAL: {
    FACEBOOK: "",
    INSTAGRAM: "",
  },
  OWNER: {
    NAME: "Josh Collins",
    YEARS_IN_BUSINESS: "5+",
  },
  CERTIFICATIONS: {
    MINORITY_OWNED: true,
    TRIBAL_CERTIFIED: true,
    CERTIFYING_ORGANIZATION: "Choctaw Nation of Oklahoma",
  },
  ADDITIONAL_KEYWORDS: [
    "Minority Owned Pressure Washing",
    "Choctaw Nation Certified Business",
    "DFW Minority Pressure Washing Company",
    "Tribal Certified Pressure Washing",
    "Minority-Owned Business DFW",
    "Native American Owned Business Texas",
  ],
};

export const TOP_CITIES_FOR_DISPLAY = [
  "Arlington",
  "Mansfield",
  "Dallas",
  "Fort Worth",
  "Plano",
  "Southlake",
  "Grapevine",
  "Colleyville",
  "Coppell",
  "Carrollton",
  "Bedford",
];
